#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Akihiko Komada <aki1770@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#
# Re-fetches the KUKSA protobuf definitions this package's gRPC stubs are
# generated from, and DIFFS them against the copies vendored in proto/.
#
#   tool/proto_sync.sh          # diff only; exit 1 if upstream has changed
#   tool/proto_sync.sh --update # overwrite proto/ with upstream, then diff
#
# WHY (and this is the sibling of tool/vss_sync.sh, deliberately):
#
#   vss_sync.sh guards the DATA MODEL — if COVESA changes a signal's unit or
#   range, the build breaks loudly rather than letting our documentation quietly
#   become untrue. That guard has existed and run in CI.
#
#   Nothing guarded the WIRE CONTRACT. lib/src/generated/ is checked-in protoc
#   output; the files say only "Generated from kuksa/val/v2/val.proto" and record
#   no ref, no sha, no date. So the question "do our stubs still match the
#   contract the databroker serves?" had no answer in this repo.
#
#   That became acute on 2026-08-24, when eclipse-kuksa/kuksa-databroker moved
#   its protos OUT of the server repo and into a standalone, independently
#   versioned repo (commit "Use kuksa-proto as a git submodule"). The contract
#   can now move without the server moving. A silent stub/contract mismatch is a
#   deserialization failure at runtime, in a vehicle, on a signal a driver's
#   warning depends on — not a compile error.
#
# WHAT THIS DOES NOT DO, stated so nobody reads more into a green run:
#   It proves the vendored .proto files match upstream. It does NOT prove
#   lib/src/generated/ was regenerated from them — run tool/generate_protos.sh
#   for that. Contract drift and stub staleness are two different failures and
#   this guard catches the first.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROTO_DIR="$ROOT/proto"
REF_FILE="$PROTO_DIR/UPSTREAM_REF"
REPO="eclipse-kuksa/kuksa-proto"
FILES=(
  kuksa/val/v1/types.proto
  kuksa/val/v1/val.proto
  kuksa/val/v2/types.proto
  kuksa/val/v2/val.proto
)

UPDATE=0
[ "${1:-}" = "--update" ] && UPDATE=1

# PROTO_REF pins the contract. Unset => track the moving branch, which is the
# honest default for a DIFF (we want to be told when upstream moves), but it is
# NOT what generation should use — generation pins.
REF="${PROTO_REF:-main}"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
drift=0
missing=0

for f in "${FILES[@]}"; do
  mkdir -p "$tmp/$(dirname "$f")"
  if ! curl -sfL "https://raw.githubusercontent.com/$REPO/$REF/$f" -o "$tmp/$f"; then
    # An unreachable upstream is UNVERIFIED, never "no drift". Fail loudly.
    echo "FETCH FAILED: $f from $REPO@$REF -- UNVERIFIED, not clean" >&2
    missing=1
    continue
  fi
  if [ ! -f "$PROTO_DIR/$f" ]; then
    echo "NOT VENDORED: $f" >&2
    drift=1
    [ "$UPDATE" = 1 ] && { mkdir -p "$PROTO_DIR/$(dirname "$f")"; cp "$tmp/$f" "$PROTO_DIR/$f"; }
    continue
  fi
  if ! diff -q "$PROTO_DIR/$f" "$tmp/$f" >/dev/null; then
    echo "DRIFT: $f" >&2
    diff -u "$PROTO_DIR/$f" "$tmp/$f" | head -40 >&2 || true
    drift=1
    [ "$UPDATE" = 1 ] && cp "$tmp/$f" "$PROTO_DIR/$f"
  fi
done

if [ "$missing" = 1 ]; then
  echo "PROTO SYNC: UNVERIFIED -- upstream could not be read. This is not a pass." >&2
  exit 2
fi

if [ "$UPDATE" = 1 ]; then
  gh api "repos/$REPO/commits/$REF" --jq '.sha' > "$REF_FILE" 2>/dev/null \
    || curl -sfL "https://api.github.com/repos/$REPO/commits/$REF" | sed -n 's/.*"sha": "\([a-f0-9]\{40\}\)".*/\1/p' | head -1 > "$REF_FILE"
  echo "PROTO SYNC: vendored proto/ updated to $REPO@$(cat "$REF_FILE")"
  echo "  ⚑ Stubs are NOT regenerated by this script. Run tool/generate_protos.sh."
  exit 0
fi

if [ "$drift" = 1 ]; then
  echo "PROTO SYNC: DRIFT -- vendored proto/ differs from $REPO@$REF" >&2
  echo "  Pinned at: $(cat "$REF_FILE" 2>/dev/null || echo '<no UPSTREAM_REF>')" >&2
  echo "  Re-vendor with: tool/proto_sync.sh --update && tool/generate_protos.sh" >&2
  exit 1
fi

echo "PROTO SYNC: clean -- proto/ matches $REPO@$REF (pinned $(cat "$REF_FILE" 2>/dev/null))"
