#!/usr/bin/env python3
"""Render the DEPENDENCIES file: header (with a COMPUTED summary) + annotated rows.
Reads annotated rows on stdin. The summary is counted, never typed by hand."""
import sys
from collections import Counter

rows = [l.rstrip("\n") for l in sys.stdin if l.strip()]
lic = Counter(r.split(", ")[1] for r in rows)
summary = "; ".join(f"{n}x {k}" for k, n in sorted(lic.items(), key=lambda kv: (-kv[1], kv[0])))

print(f"""# DEPENDENCIES — kuksa_dart_sdk runtime third-party dependencies
#
# Generated by tool/gen_dependencies.sh. Do not edit by hand.
#
# Scope:   runtime closure only (`dart pub deps --no-dev`). Dev-only packages
#          (test, lints and their transitives) are not distributed and are
#          excluded. NOTE: a dev dependency's transitives are also reported as
#          "transitive" by pub, so they must be excluded via --no-dev rather
#          than by filtering on dependency kind.
# Versions: from the resolution produced by `dart pub get` AT GENERATION TIME.
#          This is a library, so pubspec.lock is intentionally not committed
#          (.gitignore) and the resolution is therefore NOT pinned by the repo.
#          These versions are a snapshot; re-running may legitimately differ.
# Licenses: read from each package's own LICENSE file in the pub cache. An
#          unrecognised license is emitted as UNKNOWN and fails the run, so a
#          license is never inferred from metadata or assumed.
# IP note: Eclipse Dash / ClearlyDefined have no native Dart/pub type, so these
#          coordinates do not auto-resolve; the license column is this project's
#          reading of the declared license — NOT an Eclipse IP approval.
# Summary: {len(rows)} deps; {summary}.
#
# format: pub/pub.dev/-/<name>/<version>, <SPDX-license>, <status>, <source>
""")
print("\n".join(rows))
